### ISSUE TITLE
Colgar la imagen de background en un CDN

### ISSUE THREAD

**Issue by joserobleda** [joserobleda/reservaspadel#6]
Lo que mas tarda en cargar de lejos es la imagen de fondo, a ver si podemos colgarla por ahí en un CDN o algo así.

**Comment by janayama** [comment]
Que cdn me comentaste que conocias for free?

**Comment by joserobleda** [comment]
En teoria ya estamos usando cloudfare, pero no es un CDN al uso... por que supuestamente lo hace el automágico... pero no veo que este cargando esta imagen nuestra, quizás es por que al ser un background image en vez de un img... no lo sé, pero habría que mirar de ponerla en algún lado... eso seguro, que si no va muy lento...
