### ISSUE TITLE
Buscar directamente por coordenadas cuando las tengamos

### ISSUE THREAD

**Issue by joserobleda** [joserobleda/reservaspadel#8]
Atención, que esto es sacarnos la chorra y ponerla encima de la mesa, pero con mongo es así de sencillo: 

http://docs.mongodb.org/manual/reference/operator/query/near/

WHAT'S UP MADAFAKA!

![](http://i.minus.com/ieH5rw0zbvt9F.jpg)

**Comment by janayama** [comment]
jajajajajajajaja flipa flipa

2014-02-20 21:14 GMT+01:00 joserobleda notifications@github.com:

> Atención, que esto es sacarnos la chorra y ponerla encima de la mesa, pero
> con mongo es así de sencillo:
> 
> http://docs.mongodb.org/manual/reference/operator/query/near/
> 
> WHAT'S UP MADAFAKA!
> 
> https://github-camo.global.ssl.fastly.net/c526e25d63774c8c4337078d678b3be8d9856fc7/687474703a2f2f692e6d696e75732e636f6d2f696548357277307a62767439462e6a7067
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Babelbite/reservaspadel/issues/8
> .

## 

http://www.dokify.net/
_Javier Anaya_\* · *Software Engineer

## janaya@dokify.net

Síguenos en ...
 Twitter http://twitter.com/dokify  Google+ http://gplus.to/dokify

**Comment by joserobleda** [comment]
Me estaba volviendo loco por que esto no funcionaba, pero creo que el problema es que no tenemos bien los datos de latitud y longitud que sacamos de google... ¿puede ser?

**Comment by janayama** [comment]
Podría ser. Sería cuestión de coger algunos que no nos cuadren y comparar. En principio si el nombre de la calle esta bien, no debería haber demasiado error...

**Comment by joserobleda** [comment]
Puede ser que cuando sacamos las direcciones no pusiéramos el nombre de la
ciudad?

**Comment by janayama** [comment]
Como yo preguntaba a google por las coordenadas era dirección + ciudad. Es decir el repuclic space quedaba como "calle bla bla numero 5 boadilla del monte". Eso es como yo preguntaba a google.
